extern "C"
{
#include "php.h"
#include "ext/standard/info.h"
}
#include "php_qt.h"
#include "qt_arginfo.h"

#include <QtCore/QAbstractItemModel>

ZEND_METHOD(Qt_Core_QAbstractItemModel, buddy);
ZEND_METHOD(Qt_Core_QAbstractItemModel, canFetchMore);
ZEND_METHOD(Qt_Core_QAbstractItemModel, checkIndex);
ZEND_METHOD(Qt_Core_QAbstractItemModel, clearItemData);
ZEND_METHOD(Qt_Core_QAbstractItemModel, fetchMore);
ZEND_METHOD(Qt_Core_QAbstractItemModel, flags);
ZEND_METHOD(Qt_Core_QAbstractItemModel, hasChildren);
ZEND_METHOD(Qt_Core_QAbstractItemModel, hasIndex);
ZEND_METHOD(Qt_Core_QAbstractItemModel, headerData);
ZEND_METHOD(Qt_Core_QAbstractItemModel, insertColumn);
ZEND_METHOD(Qt_Core_QAbstractItemModel, insertColumns);
ZEND_METHOD(Qt_Core_QAbstractItemModel, insertRow);
ZEND_METHOD(Qt_Core_QAbstractItemModel, insertRows);
ZEND_METHOD(Qt_Core_QAbstractItemModel, moveColumn);
ZEND_METHOD(Qt_Core_QAbstractItemModel, moveColumns);
ZEND_METHOD(Qt_Core_QAbstractItemModel, moveRow);
ZEND_METHOD(Qt_Core_QAbstractItemModel, moveRows);
ZEND_METHOD(Qt_Core_QAbstractItemModel, removeColumn);
ZEND_METHOD(Qt_Core_QAbstractItemModel, removeColumns);
ZEND_METHOD(Qt_Core_QAbstractItemModel, removeRow);
ZEND_METHOD(Qt_Core_QAbstractItemModel, removeRows);
ZEND_METHOD(Qt_Core_QAbstractItemModel, setData);
ZEND_METHOD(Qt_Core_QAbstractItemModel, setHeaderData);
ZEND_METHOD(Qt_Core_QAbstractItemModel, sibling);
ZEND_METHOD(Qt_Core_QAbstractItemModel, sort);
ZEND_METHOD(Qt_Core_QAbstractItemModel, revert);
ZEND_METHOD(Qt_Core_QAbstractItemModel, submit);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onColumnsAboutToBeInserted);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onColumnsAboutToBeMoved);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onColumnsAboutToBeRemoved);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onColumnsInserted);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onColumnsMoved);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onColumnsRemoved);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onDataChanged);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onHeaderDataChanged);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onLayoutAboutToBeChanged);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onLayoutChanged);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onModelAboutToBeReset);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onModelReset);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onRowsAboutToBeInserted);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onRowsAboutToBeMoved);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onRowsAboutToBeRemoved);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onRowsInserted);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onRowsMoved);
ZEND_METHOD(Qt_Core_QAbstractItemModel, onRowsRemoved);
ZEND_METHOD(Qt_Core_QAbstractItemModel, beginInsertColumns);
ZEND_METHOD(Qt_Core_QAbstractItemModel, beginInsertRows);
ZEND_METHOD(Qt_Core_QAbstractItemModel, beginMoveColumns);
ZEND_METHOD(Qt_Core_QAbstractItemModel, beginMoveRows);
ZEND_METHOD(Qt_Core_QAbstractItemModel, beginRemoveColumns);
ZEND_METHOD(Qt_Core_QAbstractItemModel, beginRemoveRows);
ZEND_METHOD(Qt_Core_QAbstractItemModel, beginResetModel);
ZEND_METHOD(Qt_Core_QAbstractItemModel, changePersistentIndex);
ZEND_METHOD(Qt_Core_QAbstractItemModel, createIndex);
ZEND_METHOD(Qt_Core_QAbstractItemModel, endInsertColumns);
ZEND_METHOD(Qt_Core_QAbstractItemModel, endInsertRows);
ZEND_METHOD(Qt_Core_QAbstractItemModel, endMoveColumns);
ZEND_METHOD(Qt_Core_QAbstractItemModel, endMoveRows);
ZEND_METHOD(Qt_Core_QAbstractItemModel, endRemoveColumns);
ZEND_METHOD(Qt_Core_QAbstractItemModel, endRemoveRows);
ZEND_METHOD(Qt_Core_QAbstractItemModel, endResetModel);
ZEND_METHOD(Qt_Core_QAbstractItemModel, persistentIndexList);
